FROM node:20.9.0-alpine3.18 AS builder
WORKDIR /app
COPY src/package*.json ./
RUN npm install && npm cache clean --force
ENV PATH=/app/node_modules/.bin:$PATH
COPY src .
EXPOSE 3000
CMD ["npm", "run", "dev"]