version: "3.9"

services:
  client:
    container_name: react
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src/src:/app/src
      - /app/node_modules
